<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AppAny.Quartz.EntityFrameworkCore.Migrations.PostgreSQL" Version="0.5.1" />
    <PackageReference Include="Ardalis.GuardClauses" Version="5.0.0" />
    <PackageReference Include="Mediator.Abstractions" Version="3.1.0-rc.1" />
    <PackageReference Include="Mediator.SourceGenerator" Version="3.1.0-rc.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Quartz" Version="3.15.1" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.15.1" />
    <PackageReference Include="Quartz.Serialization.SystemTextJson" Version="3.15.1" />
    <PackageReference Include="WebPush" Version="1.0.12" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SharedKernel.Abstractions" Version="0.0.0-alpha.0.3" />
    <PackageReference Include="SharedKernel.AspNetCore" Version="0.0.0-alpha.0.3" />
    <PackageReference Include="SharedKernel.EntityFrameworkCore" Version="0.0.0-alpha.0.3" />
    <PackageReference Include="SharedKernel.Messaging.Abstractions" Version="0.0.0-alpha.0.3" />
    <PackageReference Include="SharedKernel.Messaging.RabbitMq" Version="0.0.0-alpha.0.3" />
    <PackageReference Include="SharedKernel.Results" Version="0.0.0-alpha.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Notifications.Infrastructure\Notifications.Infrastructure.csproj" />
  </ItemGroup>

</Project>
