---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "dopamine-kick-api.namespace" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dopamine-kick-api.fullname" . }}
  namespace: {{ include "dopamine-kick-api.namespace" . }}
  labels:
    {{- include "dopamine-kick-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dopamine-kick-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dopamine-kick-api.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dopamine-kick-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ConnectionStrings__UsersDBConnectionString
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: {{ .Values.database.userDbConnectionStringKey }}

            - name: ConnectionStrings__HabitsDBConnectionString
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: {{ .Values.database.habitsDbConnectionStringKey }}
            - name: ConnectionStrings__QuestsDBConnectionString
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: {{ .Values.database.questsDbConnectionStringKey }}
            - name: ConnectionStrings__NotificationsDBConnectionString
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: {{ .Values.database.notificationsDbConnectionStringKey }}
            - name: Redis__Password 
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.secretName }}
                  key: {{ .Values.redis.passwordKey }}
            - name: Keycloak__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.secretName }}
                  key: {{ .Values.keycloak.secretKeyName }}
            - name: WebPush__PrivateKey
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webpush.secretName }}
                  key: {{ .Values.webpush.privateKeyKeyName }}
            - name: RabbitMQ__Username
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.secretName }}
                  key: {{ .Values.rabbitmq.usernameKey }}
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.secretName }}
                  key: {{ .Values.rabbitmq.passwordKey }}
          envFrom:
            - configMapRef:
                name: dopamine-kick-api-config
          ports:
            - containerPort: 5009
              name: http
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
